version: '3.8'
services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  test-db:
    image: postgres:16.2
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_HOST=${TEST_DB_HOST}
    ports:
      - "5433:5432"
  web:
    build: .
#    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000
    command: bash -c "poetry run alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    healthcheck:
#      tests: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 10s
    depends_on:
      - db
      - test-db
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  postgres_data:
  test_postgres_data:
