"""unique fields added

Revision ID: cd132479ab68
Revises: 93089ee6d83f
Create Date: 2024-04-17 18:52:45.985028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd132479ab68'
down_revision = '93089ee6d83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
